name: cubit_form
description: Cubit Form
version: 3.0.3
homepage: https://github.com/kherel/cubit_form

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^9.0.0
  collection: ^1.18.0
  email_validator: ^2.1.17
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
