name: cubit_form
description: Cubit Form
version: 3.0.4
homepage: https://github.com/kherel/cubit_form

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  bloc: ^9.0.0
  collection: ^1.18.0
  email_validator: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
